[package]
name = "auroka_test_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
skip-test-attr = []

[dependencies]
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true

[dev-dependencies]
auroka_assertions.workspace = true
auroka_utils.workspace = true
auroka_utils_packages.workspace = true
prettyplease.workspace = true
rand.workspace = true

[lints]
workspace = true
