[workspace]
members = [
    "auroka",
    "auroka_assertions",
    "auroka_assertions_web",
    "auroka_assertions_web_page",
    "auroka_behavior",
    "auroka_test",
    "auroka_test_macro",
    "auroka_test_registry",
    "auroka_test_runner/clients/cli",
    "auroka_test_runner/core",
    "auroka_test_runner/runtimes/runtime",
    "auroka_test_runner/runtimes/vms/workerd",
    "auroka_test_web",
    "auroka_test_web_page",
    "auroka_utils",
    "auroka_utils_filesystem",
    "auroka_utils_packages",
]

resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
assert_cmd = "2.0.12"
auroka = { path = "auroka" }
auroka_assertions = { path = "auroka_assertions" }
auroka_assertions_web = { path = "auroka_assertions_web" }
auroka_assertions_web_page = { path = "auroka_assertions_web_page" }
auroka_behavior = { path = "auroka_behavior" }
auroka_test = { path = "auroka_test" }
auroka_test_macro = { path = "auroka_test_macro" }
auroka_test_registry = { path = "auroka_test_registry" }
auroka_test_runner = { path = "auroka_test_runner/clients/cli" }
auroka_test_runner_core = { path = "auroka_test_runner/core" }
auroka_test_web = { path = "auroka_test_web" }
auroka_test_web_page = { path = "auroka_test_web_page" }
auroka_utils = { path = "auroka_utils" }
auroka_utils_filesystem = { path = "auroka_utils_filesystem" }
auroka_utils_packages = { path = "auroka_utils_packages" }
chromiumoxide = "0.8"
clap = { version = "4.5", features = ["derive"] }
diff = "0.1.13"
futures = "0.3"
lazy_static = "1.4.0"
once_cell = "1.18.0"
predicates = "3.1.3"
proc-macro2 = "1.0.105"
quote = "1.0.43"
rand = "0.9.0"
regex = "1.10.0"
reqwest = "0.13.1"
serde_json = "1.0"
syn = { version = "2.0.114", features = ["full", "extra-traits"] }
tempfile = "3.24.0"
thirtyfour = "0.36"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wit-bindgen = { version = "0.50", features = ["async-spawn"] }
wit-deps = "0.6.0"
