[package]
name = "auroka_test_runner_vm_workerd"
version = "0.1.0"
edition = "2024"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0"
tempfile = "3"                                                  # To generate config.capnp on the fly
auroka_test_runner_core = { workspace = true }
tokio = { workspace = true, features = ["process", "io-util"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["time"] }
