[package]
name = "auroka_behavior"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
auroka_assertions.workspace = true
auroka_utils.workspace = true
auroka_utils_packages.workspace = true
prettyplease.workspace = true
rand.workspace = true

[lints]
workspace = true

