[package]
name = "auroka_test_runner"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "auroka_test_runner"
path = "src/main.rs"

[dependencies]
auroka_test_registry.workspace = true
clap.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
auroka_behavior.workspace = true
auroka_test.workspace = true
lazy_static.workspace = true
predicates.workspace = true
rand.workspace = true
regex.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true
